db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
web:
  build: .
  links:
   - db
  ports:
   - "8000:8000"
  environment:
    CLIQUET_CACHE_URL: postgres://postgres:postgres@db/postgres
    CLIQUET_STORAGE_URL: postgres://postgres:postgres@db/postgres
